# Generated by Django 4.2.6 on 2023-10-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_comments_bids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='listings',
            name='image_urls',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='listings',
            name='categories',
            field=models.ManyToManyField(to='auctions.category'),
        ),
    ]
