# Generated by Django 4.2.6 on 2023-10-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_listings_image_urls_listings_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='price',
            new_name='starting_bid',
        ),
        migrations.AddField(
            model_name='listings',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='listings/images/'),
        ),
    ]
